/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class rbq_wtf_lycoris_agent_instrument_impl_InstrumentationImpl */

#ifndef _Included_rbq_wtf_lycoris_agent_instrument_impl_InstrumentationImpl
#define _Included_rbq_wtf_lycoris_agent_instrument_impl_InstrumentationImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rbq_wtf_lycoris_agent_instrument_impl_InstrumentationImpl
 * Method:    getAllLoadedClasses
 * Signature: ()[Ljava/lang/Class;
 */
extern "C" __declspec(dllexport)  jobjectArray JNICALL Java_rbq_wtf_lycoris_agent_instrument_impl_InstrumentationImpl_getAllLoadedClasses
  (JNIEnv *, jobject);

/*
 * Class:     rbq_wtf_lycoris_agent_instrument_impl_InstrumentationImpl
 * Method:    retransformClasses
 * Signature: ([Ljava/lang/Class;)V
 */
extern "C" __declspec(dllexport)  void JNICALL Java_rbq_wtf_lycoris_agent_instrument_impl_InstrumentationImpl_retransformClasses
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     rbq_wtf_lycoris_agent_instrument_impl_InstrumentationImpl
 * Method:    getLoadedClasses
 * Signature: (Ljava/lang/ClassLoader;)[Ljava/lang/Class;
 */
extern "C" __declspec(dllexport)  jobjectArray JNICALL Java_rbq_wtf_lycoris_agent_instrument_impl_InstrumentationImpl_getLoadedClasses
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
